contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nextbigthing channel"
    url: https://nfcore.slack.com/channels/nextbigthing
    about: Discussion about the nf-core/nextbigthing pipeline
